[versions]
# libraries
annotations = "24.1.0"
kala-collection = "0.72.0"

# plugins
kotlin = "1.9.24"
gradleIntelliJPlugin = "1.17.3"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
kala-collection = { group = "org.glavo.kala", name = "kala-collection", version.ref = "kala-collection" }

[plugins]
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
